# Generated by Django 4.1.5 on 2023-05-01 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0003_ticket_creator_alter_ticket_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
