# Generated by Django 4.1.5 on 2023-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0004_alter_ticket_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('inprogress', 'inprogress'), ('review', 'review'), ('completed', 'completed')], max_length=30, null=True),
        ),
    ]
