# Generated by Django 4.1.5 on 2023-05-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0005_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('inprogress', 'inprogress'), ('review', 'review'), ('completed', 'completed')], default='todo', max_length=30),
        ),
    ]
