# Generated by Django 4.1.5 on 2023-06-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0007_ticketlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='github_link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
