# Generated by Django 4.1.5 on 2023-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0009_alter_ticketlog_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
