# Generated by Django 4.1.5 on 2023-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0010_ticket_github_link_alter_ticketlog_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_status',
            field=models.CharField(default='ontime', max_length=125),
        ),
    ]
