# Generated by Django 4.1.5 on 2023-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_supervisor_project_fyppanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
