# Generated by Django 4.1.5 on 2023-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='facultyid',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
