# Generated by Django 4.1.5 on 2023-01-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_designation_user_facultyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='facultyid',
            field=models.CharField(max_length=45),
        ),
    ]
