# Generated by Django 4.1.5 on 2023-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_designation_alter_user_facultyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fyppanel',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='fyppanel',
            name='facultyid',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
