# Generated by Django 4.1.5 on 2023-01-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='core.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='grade',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='intital', max_length=45),
        ),
    ]
