# Generated by Django 4.1.5 on 2023-01-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supervisor_department_alter_project_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='initial', max_length=45),
        ),
    ]
