# Generated by Django 4.1.5 on 2023-01-22 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_department_name_alter_fyppanel_facultyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
