# Generated by Django 4.1.5 on 2023-01-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_supervisor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_of_group_members',
            field=models.IntegerField(default=5),
        ),
    ]
