# Generated by Django 4.1.5 on 2023-03-26 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_notifications_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='createdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='createtime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
