# Generated by Django 4.1.5 on 2023-03-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notifications_createdate_notifications_createtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='notification',
        ),
    ]
