# Generated by Django 4.1.5 on 2023-04-04 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='grade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
    ]
