# Generated by Django 4.1.5 on 2023-04-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_teammember_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='department',
        ),
    ]
