# Generated by Django 4.1.5 on 2023-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_teammember_enrollmentno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='enrollmentno',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phoneno',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='seatno',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
    ]
