# Generated by Django 4.1.5 on 2023-04-13 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='grade',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='ongoing', max_length=45),
        ),
    ]
