# Generated by Django 4.1.5 on 2023-04-13 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_project_year_alter_project_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_of_group_members',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
