# Generated by Django 4.1.5 on 2023-04-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_project_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.project'),
        ),
    ]
