# Generated by Django 4.1.5 on 2023-04-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_teammember_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='department',
            new_name='project',
        ),
    ]
