# Generated by Django 4.1.5 on 2023-04-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_teammember_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.project'),
        ),
    ]
