# Generated by Django 4.1.5 on 2023-04-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_project_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='milestone',
            field=models.ManyToManyField(to='core.milestone'),
        ),
    ]
