# Generated by Django 4.1.5 on 2023-04-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_project_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='rubrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
