# Generated by Django 4.1.5 on 2023-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_milestone_rubrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notification',
            field=models.ManyToManyField(to='core.notification'),
        ),
    ]
