# Generated by Django 4.1.5 on 2023-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_project_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='designation',
            field=models.CharField(default=False, max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneno',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
