# Generated by Django 4.1.5 on 2023-04-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_supervisor_phone_no_remove_teammember_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(max_length=50),
        ),
    ]
