# Generated by Django 4.1.5 on 2023-04-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
