# Generated by Django 4.1.5 on 2023-04-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_project_department_alter_project_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='document_submissin_date',
            new_name='document_submission_date',
        ),
    ]
