# Generated by Django 4.1.5 on 2023-04-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_rename_document_submissin_date_milestone_document_submission_date'),
        ('core', '0057_alter_project_supervisor'),
    ]

    operations = [
    ]
