# Generated by Django 4.1.5 on 2023-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_milestone_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='marks',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='rubrics',
            field=models.JSONField(default=False),
        ),
    ]
