# Generated by Django 4.1.5 on 2023-05-06 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_milestone_rubrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
    ]
