# Generated by Django 4.1.5 on 2023-05-06 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_project_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grade',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='grade',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
    ]
