# Generated by Django 4.1.5 on 2023-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_project_grade_alter_teammember_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
