# Generated by Django 4.1.5 on 2023-05-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_notification_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.fyppanel'),
        ),
    ]
