# Generated by Django 4.1.5 on 2023-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_notification_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createtime',
            field=models.TimeField(),
        ),
    ]
