# Generated by Django 4.1.5 on 2023-05-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_notification_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.department'),
        ),
    ]
