# Generated by Django 4.1.5 on 2023-06-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.university'),
        ),
    ]
