# Generated by Django 4.1.5 on 2023-07-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='uni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.university'),
        ),
    ]
