# Generated by Django 4.1.5 on 2023-07-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_milestone_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.department'),
        ),
    ]
