# Generated by Django 4.1.5 on 2023-05-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_milestone_rubrics'),
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonework',
            name='project',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.RESTRICT, to='core.project'),
        ),
    ]
