# Generated by Django 4.1.5 on 2023-05-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_milestone_rubrics'),
        ('milestone', '0003_alter_milestonework_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonework',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='milestone_work', to='core.milestone'),
        ),
    ]
