# Generated by Django 4.1.5 on 2023-05-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_project_grade'),
        ('milestone', '0004_alter_milestonework_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestonemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(max_length=150)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
