# Generated by Django 4.1.5 on 2023-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0005_milestonemarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonemarks',
            name='marks',
            field=models.FloatField(default=50.0),
        ),
    ]
