# Generated by Django 4.1.5 on 2023-05-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0007_milestonefinalmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='milestonefinalmarks',
        ),
    ]
