# Generated by Django 4.1.5 on 2023-05-08 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milestone', '0009_milestonemarks_m_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonemarks',
            name='m_distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='m_distributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
