# Generated by Django 4.1.5 on 2023-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0010_alter_milestonemarks_m_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonework',
            name='time_status',
            field=models.CharField(default='ontime', max_length=125),
        ),
    ]
